CREATE TABLE `clientes`(
	id int(4),
	nombre varchar(45),
    localidad varchar(15),
    PRIMARY KEY (`id`));
    
    CREATE TABLE `localidades`(
	id int(2),
	localidad varchar(30),
    PRIMARY KEY (`id`));


CREATE TABLE `proveedores`(
	id int(2),
	proveedor varchar(30),
    PRIMARY KEY (`id`));
    
    CREATE TABLE `productos`(
	id int(2),
    modelo varchar(60),
    proveedor varchar(20),
    PRIMARY KEY (`id`));

INSERT INTO clientes 
VALUES (1,'Ferretería MaxiJor','San Miguel'),
(2,'Ferretería Daniel','San Miguel'),
(3,'Ferretería Serrano','San Miguel'),
(4,'Ferretería La Vieja Esquina','Muñiz'),
(5,'Ferretería Omega','Bella Vista'),
(6,'Ferretería Boulevard','Bella Vista'),
(7,'Ferretería Areguati','Grand Bourg'),
(8,'Ferretería Corralón SJS','Grand Bourg'),
(9,'Ferretería RS','Grand Bourg'),
(10,'Ferretería San Benito','Tortuguitas'),
(11,'Ferretería Grecia','Tortuguitas'),
(12,'Ferretería Am','Tortuguitas'),
(13,'Ferretería Leiva','José C. Paz'),
(14,'Ferretería FG','José C. Paz'),
(15,'Ferretería El Zonda','José C. Paz'),
(16,'Ferretería Díaz','José C. Paz'),
(17,'Ferretería Leyton','José C. Paz'),
(18,'Ferretería Juan','José C. Paz'),
(19,'Ferretería Cicconne','José C. Paz'),
(20,'Ferretería Los Romeros','José C. Paz'),
(21,'Ferretería Almaras','José C. Paz'),
(22,'Ferretería Nico','José C. Paz'),
(23,' Ferretería Lucas','José C. Paz'),
(24,'Ferretería Molino','José C. Paz'),
(25,'Artículos de ferretería Selena','José C. Paz'),
(26,'Ferretería Luisito','San Miguel'),
(27,'Ferretería Romero','San Miguel'),
(28,'Ferretería San Expedito','San Miguel'),
(29,'Ferretería Alvear','San Miguel'),
(30,'Ferretería Kuin','José C. Paz'),
(31,'Ferretería y Pesca Casa Ferrer','José C. Paz'),
(32,'Ferretería Di Prinzio','José C. Paz'),
(33,'Ferretería Los Hermanos','Tortuguitas'),
(34,'Ferretería FGS','Grand Bourg'),
(35,'Corralón FGS','Grand Bourg'),
(36,'Ferretería Lucho','Grand Bourg'),
(37,'Ferretería Danser','Grand Bourg'),
(38,'Ferretería Los Colos','Grand Bourg'),
(39,'Cerrajería Callao','Grand Bourg'),
(40,'Ferretería Marquesini','Grand Bourg'),
(41,'Ferretería Malugami','Grand Bourg'),
(42,'Ferretería Hugo','Grand Bourg'),
(43,'Ferretería Gauchito Gil','Grand Bourg'),
(44,'Ferretería Hernan','Ing. Pablo Nogués'),
(45,'Ferretería Hernan 2','Ing. Pablo Nogués'),
(46,'Ferretería Escorpio','Ing. Pablo Nogués'),
(47,'Ferretería Agustín','Ing. Pablo Nogués'),
(48,'Ferretería La Unión','Grand Bourg'),
(49,'Ferretería Otto','Grand Bourg'),
(50,'Ferretería Toto','Grand Bourg'),
(51,'Ferretería Da Costa','José C. Paz'),
(52,'Ferretería MD','José C. Paz'),
(53,'Ferretería Emanuel Hugo','José C. Paz'),
(54,'Ferretería Albrema','José C. Paz'),
(55,'Ferretería Emanuel Carlos','José C. Paz'),
(56,'Ferretería Teresa','José C. Paz'),
(57,'Ferretería Argentina','José C. Paz'),
(58,'Ferretería Acme','José C. Paz'),
(59,'Ferretería EL Galpón','José C. Paz'),
(60,'Ferretería Odisea','Tortuguitas'),
(61,'Ferretería El Felix','Pte. Derqui'),
(62,'Sanitario y Ferretería Gerard','Pte. Derqui'),
(63,'Ferretería Lencina','Pte. Derqui'),
(64,'Ferretería Lima','Pte. Derqui'),
(65,'Ferretería La Roca','Del Viso'),
(66,'Ferretería AyR','Del Viso'),
(67,'Ferretería El Doreado','Del Viso'),
(68,'Ferretería AyR 2','Del Viso'),
(69,'Ferretería Totaro','José C. Paz');

INSERT INTO localidades 
VALUES (1,'Tortuguitas'),
(2,'San Miguel'),
(3,'Grand Bourg'),
(4,'Del Viso'),
(5,'Pte. Derqui'),
(6,'José C. Paz'),
(7,'Bella Vista'),
(8,'Muñiz'),
(9,'Ing. Pablo Nogués');

INSERT INTO proveedores
VALUES (1,'Talleres Fumaca'),
(2,'Sabelcort'),
(3,'Importadora Luque'),
(4,'Metalurgica Canton'),
(5,'Fullroller'),
(6,'Fijaciones Py'),
(7,'O.I.R.'),
(8,'Parts S.A.'),
(9,'Inter Rueda S.A.'),
(10,'FCH S.A.');

INSERT INTO productos
VALUES (1,'bisagra t/munic carp zink amar 100*88 d/c','Talleres Fumaca'),			
	(2,'bisagras 5005 nacion bronceadas 101m','Talleres Fumaca'),			
	(3,'bisagras mosqueras blanca c/u','Talleres Fumaca'),			
	(4,'bisagras 5005 nacion bronceadas 101m','Talleres Fumaca'),			
	(5,'bisagras 5005 chinas pulidas 88m','Talleres Fumaca'),			
	(6,'bisagras 5005 chinas bronceado 50m','Talleres Fumaca'),			
	(7,'bisagras 5005 nacionales pulidas 38m','Talleres Fumaca'),			
	(8,'bisagras mosqueras negra c/u','Talleres Fumaca'),			
	(9,'bisagras mosqueras zinkada c/u','Talleres Fumaca'),			
	(10,'bisagras rev atornillar 2*5*11/2 zink amarilla','Talleres Fumaca'),			
    (11,'tender abanico lateral','Sabelcort'),			
	(12,'tender abanico vertical','Sabelcort'),			
	(13,'tender de colgar de 50 cn con ala','Sabelcort'),			
	(14,'tender de colgar de 50 cn sin ala','Sabelcort'),			
	(15,'tender de pie simple de 9 varillas','Sabelcort'),			
	(16,'tender de techo chico','Sabelcort'),			
	(17,'tender de techo grande','Sabelcort'),			
	(18,'tender extensible de 100 cn 9 varillas','Sabelcort'),			
	(19,'tender pie doble 9 varillas c/parrilla','Sabelcort'),			
	(20,'tender rodante grande','Sabelcort'),			
    (21,'bocha para caño extensible comun 10 pares','Importadora Luque'),			
	(22,'bocha para caño extensible de lujo el par','Importadora Luque'),			
	(23,'caño curvo 0.75 + 1.75 met pulido','Importadora Luque'),			
	(24,'caño curvo 0.75 + 0.75 met pulido','Importadora Luque'),			
	(25,'caño curvo 0.90+0.90+0.90 met pintado','Importadora Luque'),			
	(26,'caño extensible estriado 1.30mts anodizado','Importadora Luque'),			
	(27,'caño extensible estriado 2.00mts pintado','Importadora Luque'),			
	(28,'caño extensible hasto 1.30 de lujo pintado','Importadora Luque'),			
	(29,'caño extensible hasto 1.30 met pintado','Importadora Luque'),			
	(30,'caño extensible hasto 2.60 de lujo met pintado','Importadora Luque'),			
    (31,'bisagras muni mixta ator/sol 100*62*3 2r','Metalurgica Canton'),		
	(32,'bisagras munic mixta ator/sol 100*65*3 2r','Metalurgica Canton'),			
	(33,'bisagras munic mixta ator/sol 75*75*3 2r','Metalurgica Canton'),			
	(34,'bisagras munic 1 ala corta sol 100*62*3 2r','Metalurgica Canton'),			
	(35,'bisagras munic 1 ala corta sol 124*65*3 4r','Metalurgica Canton'),			
	(36,'bisagras munic 1 ala corta sol 78*54*3 2r','Metalurgica Canton'),			
	(37,'bisagras munic ala corta sol 100*37*2,5 2r','Metalurgica Canton'),			
	(38,'bisagras munic ala corta sol 124*37*3 3r','Metalurgica Canton'),			
	(39,'bisagras muni atorni h/zink 124*100*3 4r','Metalurgica Canton'),			
	(40,'bisagras munic bronce plat 100*75*3 2r','Metalurgica Canton'),			
    (41,'ruedas hierro a rodillo en v,u,r,p105m','Fullroller'),			
	(42,'ruedas hierro a rodillo en v,u,r,p120m','Fullroller'),			
	(43,'ruedas hierro a rodillo en v,u,r,p150m','Fullroller'),			
	(44,'ruedas hierro a rodillo en v,u,r,p180m','Fullroller'),			
	(45,'ruedas hierro a rodillo en v,u,r,p50m','Fullroller'),			
	(46,'ruedas hierro con 1 ruleman en v,u,r,p50m','Fullroller'),			
	(47,'ruedas hierro con 1 ruleman en v,u,r,p90m','Fullroller'),			
	(48,'ruedas hierro con 1 ruleman en v,u,r,p70 ECONOI','Fullroller'),			
	(49,'ruedas hierro con 1 ruleman en v,u,r,p90 ECONOMI','Fullroller'),			
	(50,'ruedas hierro con 1 ruleman en v,u,r,P120ECONO','Fullroller'),			
    (51,'tarugos PY espiral p/yeso *250unid','Fijaciones Py'),			
	(52,'tarugos PY espiral p/yeso *250unid de 6 econom','Fijaciones Py'),			
	(53,'tarugos PY espiral p/yeso *250unid de 8 econom','Fijaciones Py'),			
	(54,'tarugos PY polietileno mariposa 8-10*250 und','Fijaciones Py'),			
	(55,'tarugos PY polietileno mariposa 8m 20*250unid','Fijaciones Py'),			
	(56,'tarugos PY polietileno espiga 6*1000unid','Fijaciones Py'),			
	(57,'tarugos PY polietileno espiga 8*500unid','Fijaciones Py'),			
	(58,'tarugos PY polietileno espiga 10*250unid','Fijaciones Py'),			
	(59,'tarugos PY polietileno espiga 12*100unid','Fijaciones Py'),			
	(60,'tarugos PY polietileno espiga 14*50unid','Fijaciones Py'),			
    (61,'regatones angulo 1','O.I.R.'),		
	(62,'regatones angulo 11/4','O.I.R.'),			
	(63,'regatones angulo 7/8','O.I.R.'),			
	(64,'regatones cuadrados 20*20','O.I.R.'),			
	(65,'regatones cuadrados 35*35','O.I.R.'),			
	(66,'regatones de interior 1" aletado','O.I.R.'),			
	(67,'regatones de interior 11/4 c/tuerca','O.I.R.'),			
	(68,'regatones exterior 1" largo','O.I.R.'),			
	(69,'regatones exterior 13/8 corto','O.I.R.'),			
	(70,'regatones rectangular 20*10','O.I.R.'),			
    (71,'pasador cerrojo c/perilla zink 10cn','Parts S.A.'),			
	(72,'pasador cerrojo c/perilla zink 17cn','Parts S.A.'),			
	(73,'pasador cerrojo charolado 35m 12unid','Parts S.A.'),			
	(74,'pasador cerrojo charolado 40m 12unid','Parts S.A.'),			
	(75,'pasador cerrojo charolado 47m 12unid','Parts S.A.'),			
	(76,'pasador cerrojo charolado 57m 12unid','Parts S.A.'),			
	(77,'pasador cerrojo zink 35m 12unid','Parts S.A.'),			
	(78,'pasador cerrojo zink 40m 12unid','Parts S.A.'),			
	(79,'pasador cerrojo zink 47m 12unid','Parts S.A.'),			
	(80,'pasador cerrojo zink 57m 12unid','Parts S.A.'),			
    (81,'rueda doble plana c/soporte u 35m','Inter rueda S.A.'),		
	(82,'rueda lavarropa rosca metal','Inter rueda S.A.'),			
	(83,'rueda para futom','Inter rueda S.A.'),			
	(84,'rueda pol giratoria pasante 80m','Inter rueda S.A.'),			
	(85,'rueda goma giratoria pasante 40','Inter rueda S.A.'),			
	(86,'rueda pol 100m giratoria pasante c/freno','Inter rueda S.A.'),			
	(87,'rueda pol c/base y municion 100m','Inter rueda S.A.'),			
	(88,'rueda pol c/base y municion c/freno 100m','Inter rueda S.A.'),			
	(89,'rueda goma c/base y municion 40','Inter rueda S.A.'),			
	(90,'rueda goma c/base y municion 80','Inter rueda S.A.'),			
    (91,'pasador cerrojo c/porta candado 15cn c/u','FCH S.A.'),			
	(92,'pasador cerrojo c/porta candado 20cn c/u','FCH S.A.'),			
	(93,'pasador cerrojo c/porta candado 30cn c/u','FCH S.A.'),			
	(94,'pasador cerrojo c/porta candado 40cn c/u','FCH S.A.'),			
	(95,'pasador cerrojo c/porta candado eco 10cnc/u','FCH S.A.'),			
	(96,'pasador cerrojo c/porta candado eco 17cnc/u','FCH S.A.'),			
	(97,'pasador de piso 15cn c/u','FCH S.A.'),			
	(98,'pasador de piso 30cn c/u','FCH S.A.'),			
	(99,'pasador de piso 40cn c/u','FCH S.A.'),			
	(100,'pasador de piso 50cn c/u','FCH S.A.');			